language: node_js
node_js:
- 8.11.3
before_install:
- openssl aes-256-cbc -K $encrypted_7700b37223df_key -iv $encrypted_7700b37223df_iv
  -in test_key.enc -out /root/.ssh/test_key -d
- chmod 600 /root/.ssh/test_key
scripts:
  - npm run test
after_success:
  # - npm prune --production  # 删除devDependencies 
  # - tar -jcf build.tar.bz2 *    # 打包并压缩代码
  # - scp indoor-server.tar.bz2 jingsam@102.201.64.94:~/